# Copyright 2016 Yahoo Inc.
# Licensed under the terms of the New-BSD license. Please see LICENSE file in the project root for terms.

swagger: '2.0'
info:
  $ref: ./info/index.yaml
  title: 'Flickr API'
basePath: /services
host: api.flickr.com
schemes:
  - https
consumes:
  - multipart/form-data
produces:
  - application/json
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
